// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tnnjkbipydrhccwxofzm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRubmprYmlweWRyaGNjd3hvZnptIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY2MjQ5MDUsImV4cCI6MjA3MjIwMDkwNX0.NP7Z-dZTM1ss1n4sB1DKEFu9XNMFEzAjuzTEIvOAsAY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});